/**
 * Схема песочницы каждого квеста для автодополнения в SQL-редакторе:
 * таблица → список колонок. Используется только клиентом (подсказки
 * в CodeMirror), поэтому здесь не текстов заданий и решений — просто
 * имена, безопасные для показа до решения шага.
 */
export const QUEST_SQL_SCHEMAS: Record<string, Record<string, string[]>> = {
  "midnight-express": {
    passengers: ["id", "name", "age", "occupation", "wagon", "coupe"],
    tickets: [
      "id",
      "passenger_id",
      "from_station",
      "to_station",
      "price",
      "purchased_at",
    ],
    stations: ["id", "name", "arrival_time", "stop_minutes"],
    conductor_log: ["id", "wagon", "event_time", "note"],
    luggage: ["id", "passenger_id", "description", "weight_kg"],
    onboard_check: ["passenger_id", "wagon", "checked_at"],
  },
  "prometheus-beginner": {
    sectors: [
      "sector_id",
      "sector_code",
      "sector_name",
      "deck_number",
      "sector_type",
      "pressure_kpa",
      "temperature_c",
      "power_status",
      "contamination_level",
      "is_accessible",
    ],
    system_events: [
      "event_id",
      "system_id",
      "sector_id",
      "event_type",
      "severity",
      "event_value",
      "event_message",
      "recorded_at",
    ],
    crew_members: [
      "crew_id",
      "full_name",
      "role",
      "department",
      "badge_id",
      "access_level",
      "official_status",
      "cabin_sector_id",
    ],
    crew_shifts: [
      "shift_id",
      "crew_id",
      "sector_id",
      "shift_start",
      "shift_end",
      "shift_role",
    ],
    access_logs: [
      "access_id",
      "badge_id",
      "sector_id",
      "access_time",
      "access_result",
      "entry_type",
      "device_id",
    ],
    communications: [
      "message_id",
      "sender_crew_id",
      "sender_type",
      "channel",
      "message_type",
      "message_text",
      "sent_at",
      "voice_signature",
      "is_corrupted",
    ],
    ai_commands: [
      "command_id",
      "command_type",
      "target_system_id",
      "target_sector_id",
      "command_text",
      "priority",
      "source_directive",
      "executed_at",
      "was_overridden",
    ],
    medical_scans: [
      "scan_id",
      "crew_id",
      "sector_id",
      "heart_rate",
      "oxygen_level",
      "body_temperature",
      "tissue_anomaly",
      "medical_status",
      "scanned_at",
    ],
  },
  prometheus: {
    sectors: [
      "sector_id",
      "sector_code",
      "sector_name",
      "deck_number",
      "sector_type",
      "pressure_kpa",
      "temperature_c",
      "power_status",
      "contamination_level",
      "is_accessible",
    ],
    sector_connections: [
      "connection_id",
      "from_sector_id",
      "to_sector_id",
      "door_status",
      "required_access_level",
      "travel_time_sec",
      "is_pressurized",
    ],
    ship_systems: [
      "system_id",
      "system_name",
      "system_type",
      "sector_id",
      "status",
      "power_required",
      "priority_level",
      "last_service_at",
    ],
    system_events: [
      "event_id",
      "system_id",
      "sector_id",
      "event_type",
      "severity",
      "event_value",
      "event_message",
      "recorded_at",
    ],
    crew_members: [
      "crew_id",
      "full_name",
      "role",
      "department",
      "badge_id",
      "access_level",
      "official_status",
      "cabin_sector_id",
    ],
    crew_shifts: [
      "shift_id",
      "crew_id",
      "sector_id",
      "shift_start",
      "shift_end",
      "shift_role",
    ],
    access_logs: [
      "access_id",
      "badge_id",
      "sector_id",
      "access_time",
      "access_result",
      "entry_type",
      "device_id",
    ],
    communications: [
      "message_id",
      "sender_crew_id",
      "sender_type",
      "channel",
      "message_type",
      "message_text",
      "sent_at",
      "voice_signature",
      "is_corrupted",
    ],
    medical_scans: [
      "scan_id",
      "crew_id",
      "sector_id",
      "heart_rate",
      "oxygen_level",
      "body_temperature",
      "tissue_anomaly",
      "medical_status",
      "scanned_at",
    ],
    cargo_containers: [
      "container_id",
      "container_code",
      "declared_category",
      "sector_id",
      "seal_status",
      "loaded_at",
      "opened_at",
      "opened_by_badge",
      "corporate_clearance",
    ],
    cargo_items: [
      "item_id",
      "container_id",
      "item_code",
      "item_name",
      "item_category",
      "quantity",
      "hazard_class",
      "is_declared",
      "storage_temperature",
    ],
    maintenance_drones: [
      "drone_id",
      "drone_code",
      "drone_type",
      "current_sector_id",
      "status",
      "controlled_by",
      "last_contact_at",
    ],
    drone_tasks: [
      "task_id",
      "drone_id",
      "sector_id",
      "task_type",
      "material_code",
      "ordered_by",
      "task_status",
      "started_at",
      "completed_at",
    ],
    biohazard_events: [
      "bio_event_id",
      "sector_id",
      "threat_level",
      "movement_count",
      "organic_mass",
      "sensor_status",
      "detected_at",
    ],
    ai_commands: [
      "command_id",
      "command_type",
      "target_system_id",
      "target_sector_id",
      "command_text",
      "priority",
      "source_directive",
      "executed_at",
      "was_overridden",
    ],
    escape_pods: [
      "pod_id",
      "pod_code",
      "pod_type",
      "sector_id",
      "status",
      "fuel_percent",
      "oxygen_minutes",
      "hull_integrity",
      "launch_lock",
      "capacity",
    ],
    pod_diagnostics: [
      "diagnostic_id",
      "pod_id",
      "subsystem_name",
      "status",
      "measured_value",
      "checked_at",
    ],
  },
};

export function getQuestSqlSchema(
  questSlug: string
): Record<string, string[]> | undefined {
  return QUEST_SQL_SCHEMAS[questSlug];
}
