"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";

const inputClass = "w-full rounded-xl border-2 border-faded-gray px-4 py-3 text-body font-medium text-charcoal outline-none focus:border-spark-blue";

export function ForgotPasswordForm() {
  const [email, setEmail] = useState(""); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/auth/forgot-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const data = await response.json() as { ok: boolean; message?: string; error?: string }; if (data.ok) setMessage(data.message ?? "Проверь почту."); else setError(data.error ?? "Не удалось отправить ссылку."); } catch { setError("Не удалось связаться с сервером."); } finally { setLoading(false); } }
  if (message) return <div className="mx-auto max-w-[440px] rounded-[20px] border-2 border-[#cceeb4] bg-[#f2ffe9] p-7 text-center"><p className="text-4xl">✉️</p><h2 className="mt-4 text-subheading font-black text-charcoal">Проверь почту</h2><p className="mt-2 text-body font-medium text-[#53723d]">{message}</p><Link href="/login" className="mt-5 inline-flex font-extrabold text-spark-blue">Вернуться ко входу →</Link></div>;
  return <form onSubmit={submit} className="mx-auto max-w-[400px]"><label className="mb-1.5 block text-caption font-bold uppercase text-pencil-gray">Email аккаунта</label><input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" className={inputClass} />{error && <p className="mt-3 text-body font-bold text-[#d63b3b]">{error}</p>}<button disabled={loading} className="mt-5 w-full rounded-xl bg-eager-green px-6 py-3 text-nav-label font-extrabold uppercase text-paper-white disabled:opacity-50">{loading ? "Отправляю…" : "Получить ссылку"}</button><p className="mt-5 text-center text-body font-medium text-pencil-gray"><Link href="/login" className="font-bold text-spark-blue">Вернуться ко входу</Link></p></form>;
}

export function ResetPasswordForm({ token }: { token: string }) {
  const router = useRouter(); const [password, setPassword] = useState(""); const [repeat, setRepeat] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (password !== repeat) return setError("Пароли не совпадают."); setLoading(true); try { const response = await fetch("/api/auth/reset-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, password }) }); const data = await response.json() as { ok: boolean; error?: string }; if (!data.ok) return setError(data.error ?? "Не удалось изменить пароль."); router.push("/account"); router.refresh(); } catch { setError("Не удалось связаться с сервером."); } finally { setLoading(false); } }
  if (!token) return <div className="mx-auto max-w-[440px] rounded-xl border-2 border-[#ffcaca] bg-[#fff4f4] p-6 text-center"><p className="font-extrabold text-[#c83737]">В ссылке нет токена восстановления.</p><Link href="/forgot-password" className="mt-4 inline-flex font-bold text-spark-blue">Запросить новую ссылку</Link></div>;
  return <form onSubmit={submit} className="mx-auto max-w-[400px]"><label className="mb-1.5 block text-caption font-bold uppercase text-pencil-gray">Новый пароль</label><input type="password" minLength={8} required value={password} onChange={(e) => setPassword(e.target.value)} className={inputClass} placeholder="Минимум 8 символов" /><label className="mb-1.5 mt-4 block text-caption font-bold uppercase text-pencil-gray">Повтори пароль</label><input type="password" minLength={8} required value={repeat} onChange={(e) => setRepeat(e.target.value)} className={inputClass} placeholder="Ещё раз" />{error && <p className="mt-3 text-body font-bold text-[#d63b3b]">{error}</p>}<button disabled={loading} className="mt-5 w-full rounded-xl bg-eager-green px-6 py-3 text-nav-label font-extrabold uppercase text-paper-white disabled:opacity-50">{loading ? "Сохраняю…" : "Сохранить пароль"}</button></form>;
}
